# Generated by Django 6.0.6 on 2026-06-28 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('es_administrador', models.BooleanField(default=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AULA', 'Aula'), ('OFICINA', 'Oficina')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='api.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='NodoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('PENDIENTE_ABRIR', 'Pendiente abrir'), ('CERRADA', 'Cerrada'), ('PENDIENTE_CERRAR', 'Pendiente cerrar'), ('FORZADA', 'Forzada')], max_length=30)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('espacio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_acceso', to='api.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_permitidos', models.CharField(max_length=50)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='api.espacio')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaNFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_inactivacion', models.DateField(blank=True, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_nfc', to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_puerta', models.CharField(choices=[('ABIERTA', 'Abierta'), ('PENDIENTE_ABRIR', 'Pendiente abrir'), ('CERRADA', 'Cerrada'), ('PENDIENTE_CERRAR', 'Pendiente cerrar'), ('FORZADA', 'Forzada')], max_length=30)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('ABRIR', 'Abrir'), ('CERRAR', 'Cerrar')], max_length=10)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='api.espacio')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='api.nodoacceso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='api.persona')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='api.tarjetanfc')),
            ],
        ),
    ]
