# Generated by Django 6.0.6 on 2026-06-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodoacceso',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodoacceso',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('PENDIENTE_ABRIR', 'Pendiente abrir'), ('CERRADA', 'Cerrada'), ('PENDIENTE_CERRAR', 'Pendiente cerrar'), ('FORZADA', 'Forzada')], default='CERRADA', max_length=30),
        ),
        migrations.CreateModel(
            name='EventoMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_mqtt', to='api.nodoacceso')),
            ],
        ),
    ]
