# Generated by Django 6.0.6 on 2026-06-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nodoacceso_last_seen_alter_nodoacceso_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='autorizado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='acceso',
            name='request_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
